Update to 21.08 runtime, and use our own libs
flathub/com.poweriso.PowerISO pull request #2
Opened 2021-12-22 00:17 UTC by tinywrkb

* Bump to the latest 21.08 Freedesktop runtime
* Use runtime's libs as much as possible, and add libbsd
* Set interpreter with patchelf to the runtime's one
* Drop unneeded wrapper script
* Unset QT_QPA_PLATFORM to avoid having the app break when user set it
  globally to wayland. This is not an issue with KDE Plasma, but it's a
  good service to the user
* Add f-e-d-c properties, and drop the unsupported JSON comment which
  will be removed by f-e-d-c
* Install icon to the hicolor theme

This needs to be tested to confirm that nothing is broken. As far as I can tell, it working correctly.

2021-12-22 00:30 UTC, tinywrkb commented
I'm not sure if libbsd is actually needed. I added it as the app ship it, but at least when opening an image and extracting files, libbsd is not being used.

2021-12-28 00:49 UTC, tinywrkb commented
/ping @hadess

2022-05-23 12:35 UTC, hadess commented
Thanks for the patches and updating the PR. Can you please split up the changes further, in a way that the package stays buildable, but the patches are small and trivial?

2022-06-30 14:19 UTC, tinywrkb commented
@hadess sorry for the late reply. I think this should do it.

2022-07-01 08:09 UTC, hadess requested changes

2022-07-01 08:09 UTC, hadess commented on com.poweriso.PowerISO.json
> +        "--socket=x11"
Please don't reorder items that don't need to be.

2022-07-01 08:09 UTC, hadess commented on com.poweriso.PowerISO.json
> +        /* Only supports X11 with the builtin Qt */
Again with the reordering.

2022-07-01 08:09 UTC, hadess commented on com.poweriso.PowerISO.json
> -        /* Only supports X11 with the builtin Qt */
It's unsupported by flatpak-external-data-checker. It's supported by Flatpak, and will work just fine. Please leave it as-is.

2022-07-01 08:09 UTC, hadess commented on com.poweriso.PowerISO.json
> +            "name": "icu",
Please explain in the commit message why we need to compile those modules ourselves. I would also have preferred separate commits for each one of the modules.

2022-09-29 12:41 UTC, hadess approved these changes

2022-09-29 12:51 UTC, merged